
const querry = `CREATE TABLE IF NOT EXISTS eventsdata (
	id varchar(100) PRIMARY KEY,
	USERID varchar(100),
	EVENTNAME TEXT NOT NULL,
	EVENTDATE TEXT NOT NULL,
	EVENTAMOUNT TEXT NOT NULL,
	EVENTLOCATION TEXT NOT NULL,
	EVENTTIME TEXT NOT NULL,
	EVENTABOUT TEXT NOT NULL,
	EVENTHIGHLIGHT TEXT DEFAULT NULL,
	EVENTTYPE varchar(100) DEFAULT 'Public',
	EVENTCREATEDAT TEXT default null,
    foreign key (userId) references userdata(id) on delete set null on update cascade
)`