
const querry = `CREATE TABLE IF NOT EXISTS eventTicket (
	id varchar(100) PRIMARY key ,
	INVITEUSERNAME TEXT NOT NULL,
	INVITEUSEREMAIL varchar(500) NOT NULL,
	INVITEUSERNUMBER TEXT,
	EVENTID varchar(100) NOT NULL,
	EVENTUSERID varchar(100) NOT NULL,
    QRURL TEXT DEFAULT NOT NULL,
    FILENAME TEXT DEFAULT NOT NULL,
	CREATEDAT TEXT DEFAULT NULL
)`
