
const querry = `CREATE TABLE IF NOT EXISTS userdata (
	id varchar(100) PRIMARY key ,
	USERNAME TEXT NOT NULL,
	USEREMAIL varchar(500) NOT NULL unique,
	USERPASS TEXT NOT NULL,
	COUNTRY varchar(200) DEFAULT 'India',
	PROFILEPIC TEXT DEFAULT NULL,
	USERNUMBER TEXT DEFAULT NULL,
	CREATEDAT TEXT DEFAULT NULL
)`